### ISSUE TITLE
Adding Tap Gesture recogniser

### ISSUE THREAD

**Issue by anksinm** [yoavlt/LiquidFloatingActionButton#10]
I would like to know when the floating action cell is tapped so that i can close it programmatically. However, adding a tap gesture recognizer to the floating cell 'breaks' it. In the sense that it wont open. Is this a know issue? is there a fix around it?

**Comment by yoavlt** [comment]
How about `floatingActionButton.close()`? :P

**Comment by anksinm** [comment]
Hey, thanks for the reply. Calling the close function if its not open is of no use. So I am planning to know somehow if its open or not and then if its open, call the close function.

**Comment by yoavlt** [comment]
LiquidFloatingActionButton has `isClosed` method, but it may corrupt during animation.
I added `isOpening` property to LiquidFloatingActionButton in `swift-2.0` branch. Could you try it?

**Comment by anksinm** [comment]
Sure. just give me a few mins.

**Comment by anksinm** [comment]
Hey, this works great. But its only useful when the animation is in progress. After that, its back to original. Could we try some other way?

**Comment by yoavlt** [comment]
Awesome!! Thanks! :+1:

**Comment by returnzer0** [comment]
Hi, noob question but where would you know that the LiquidFloatingActionButton is about to open or close? where in code would that be put? Im having a hard time figuring it out. Thanks

**Comment by returnzer0** [comment]
If anyone is looking for the same answer as me, this is what I ended up doing. I make the background black when someone presses on the floating action button. 

`// open all cells
    open func open() {
        
        darkView = UIView(frame: (self.superview?.frame)!)
        darkView.backgroundColor = UIColor.black
        darkView.layer.zPosition = 99
        darkView.alpha = 0.0
        
        // This depends on how many subviews you have. Figure out your index.
        self.superview?.insertSubview(darkView, at: 8)

        UIView.animate(withDuration: 0.5) { () -> Void in
            self.darkView.alpha = 0.75
        }
        
        // rotate plus icon
        CATransaction.setAnimationDuration(0.8)
        self.plusLayer.transform = CATransform3DMakeRotation((CGFloat(M_PI) * rotationDegrees) / 180, 0, 0, 1)

        let cells = cellArray()
        for cell in cells {
            insertCell(cell)
        }

        self.baseView.open(cells)

        
        self.isClosed = false
    }

    // close all cells
    open func close() {
        
        UIView.animate(withDuration: 0.5) { () -> Void in
            self.darkView.alpha = 0.0
        }
        
        darkView.removeFromSuperview()
        // rotate plus icon
        CATransaction.setAnimationDuration(0.8)
        self.plusLayer.transform = CATransform3DMakeRotation(0, 0, 0, 1)
    
        self.baseView.close(cellArray())
        
        self.isClosed = true
    }
`
