### ISSUE TITLE
installation use Carthage

### ISSUE THREAD

**Issue by afishhhhh** [yoavlt/LiquidFloatingActionButton#100]
write `github "yoavlt/LiquidFloatingActionButton"` in Cartfile
run command `carthage update` with error "Dependency "LiquidFloatingActionButton" has no shared framework schemes"

**Comment by qu4sar** [comment]
idem for me

**Comment by rushilMethsof** [comment]
same for me , any updates on the matter?

**Comment by haithngn** [comment]
I have just make a folk into https://github.com/haithngn/LiquidFloatingActionButton then mark shared for scheme LiquidFloatingActionButton iOS 8.0 so now it's supported Carthage.

@yoavlt please update scheme for supporting Carthage dependence manager
it's so helpful.
Thanks,

**Comment by yoavlt** [comment]
Thanks @haithngn ! 👍
