### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by Big-al** [yoavlt/LiquidFloatingActionButton#13]
Hey,

Im getting no less than 7 fatal errors and 7 warnings when trying to build after importing. Im using Objective C, and importing the swift file into my app - but thats not the problem. the problems are all within the Pod project itself - i get 7 "Method does not override any method from its superclass" - is there a fix? or did i just suck at importing? :-)

![skaermbillede 2015-10-11 kl 17 21 49](https://cloud.githubusercontent.com/assets/7080878/10417463/b5135b5c-703c-11e5-9adb-5b58860e1cb2.png)

**Comment by elilien** [comment]
Hi @Big-al , I think you should check out the Swift-2.0 branch. ;-)

**Comment by Big-al** [comment]
Hey! thanks for the quick response! i just add branch: 'swift-2.0' to the pod document in the project right? :D sorry - im so very new to pods, but its awesome!

**Comment by yoavlt** [comment]
Could you show me your `Podfile` ?

**Comment by elilien** [comment]
Hi @yoavlt , I'm now using it in my Objective-C project and it works well, I think @Big-al should use pod's "use_frameworks!" command to install the framework, in my Xcode 7 I set my pod file as below:

`source 'https://github.com/CocoaPods/Specs.git'`
`use_frameworks!`
`pod 'LiquidFloatingActionButton', :git => 'https://github.com/yoavlt/LiquidFloatingActionButton.git', :branch => 'swift-2.0'`

**Comment by yoavlt** [comment]
Thank you @elilien :+1:

**Comment by elilien** [comment]
You're welcome ;-) I should thank you very much to write such an excellent Action Button! @yoavlt

**Comment by Big-al** [comment]
S now im getting this - maybe im a bit retarded, but we all gotta learn from somewhere :D 
![skaermbillede 2015-10-12 kl 14 58 29](https://cloud.githubusercontent.com/assets/7080878/10428463/eec7056e-70f1-11e5-934c-47d5799acec5.png)

**Comment by elilien** [comment]
No no no, why you add en "end" on the end of the file?

**Comment by Big-al** [comment]
it was there when i started the prject - it worked when i tried last time :-)

**Comment by Big-al** [comment]
Allright! it looks much better now without the "end" - now im getting another error ! (But less than before!) This time it seems like an update problem. Ive tried to update cocoa pods and I've tried to reinstall the pod, but none of those work :
![skaermbillede 2015-10-12 kl 21 00 56](https://cloud.githubusercontent.com/assets/7080878/10436073/600df3a4-7124-11e5-92a3-1c7c0820c63c.png)

**Comment by yoavlt** [comment]
Could you try as follows?

1. Write Podfile like this.
```ruby
xcodeproj 'yourprojectfile.xcodeproj'
use_frameworks!
target 'YourProjectName' do
pod 'LiquidFloatingActionButton', :git => 'https://github.com/yoavlt/LiquidFloatingActionButton.git', :branch => 'swift-2.0'
end
```

2. Run `pod install` in your terminal.

**Comment by Big-al** [comment]
AWESOME WORK! Thanks a billion! my entire cocoa pods installation was flawed, so i had to go through the trouble of uninstalling it completely first, and recreating my project without cocoa pods installed before i could then reinstall ruby, cocoa pods, xcode and everything else once again! But i finally got to the end of it today and tried you pod file, and it worked! Now i have to figure out how to implement it in my project - but thats a whole other story :-) :+1:

**Comment by yoavlt** [comment]
It sounds great! I close this issue.
