### ISSUE TITLE
Can we change plus icon?

### ISSUE THREAD

**Issue by osmantuna** [yoavlt/LiquidFloatingActionButton#14]
Thank you for making this. I am using this button kinda side menu. So, i would like to change initial "plus" icon to something more like "list" type icon or something custom i want. I attempted to do that but failed. At least if you can tell where it is initialised, i would try to change.

**Comment by yoavlt** [comment]
Thank you for reporting issue! But, it is not supported yet.
How do you want to change it? Do you want to apply like `UIImage`?

**Comment by osmantuna** [comment]
UIImage or Label can do. I can use image file or font-awesome for label

**Comment by gishanthad** [comment]
Hi , Im using this for my App. its really amazing. but i need to customise the initial Floating button. (Plus Button). I tried by changing the Inherited class of the LiquidFloatingButton as UIButton. but nothing happend. if you can tell me how can i change it then it will be a super awesome. as @osmantuna mentioned i really need to use UIImage for the Plus Button.

**Comment by apryiomka** [comment]
Hi, i need to change the image to. The "default" image is not sufficient as it doesn't match the design of the app. Is there a way to change it somehow?

Thanks,
Alex.

**Comment by yoavlt** [comment]
It works now in `swift-2.0` branch. Thank you @florianpreknya !
