### ISSUE TITLE
Cocoapods Updation error

### ISSUE THREAD

**Issue by suhailrashidbhat** [yoavlt/LiquidFloatingActionButton#17]
Following error was encountered when updating pods: 

$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `LiquidFloatingActionButton (~> 0.1)` required by `Podfile`

Specs satisfying the `LiquidFloatingActionButton (~> 0.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by yoavlt** [comment]
I think deployment target of your project is lower than iOS8.0.
