### ISSUE TITLE
Does the current implementation support top to bottom animation?

### ISSUE THREAD

**Issue by Hxucaa** [yoavlt/LiquidFloatingActionButton#2]
I really love the animation. I just have one question. Does the current implementation support animating from top to bottom? In my use case, the button would be place on the top right of the screen.

**Comment by yoavlt** [comment]
Thank you for your issue. I supported this feature! Please update my library then, 
```swift:
floationgButton.animateStyle = .Down
```

**Comment by BoilingLime** [comment]
`animateStyle` is not accessible from Objective-C code.
