### ISSUE TITLE
Does not compile on Xcode 7.1

### ISSUE THREAD

**Issue by markgk** [yoavlt/LiquidFloatingActionButton#20]
6 errors , 8 warnings on 0.1.2 which I thought was the swift 2.0 branch

for example the 3 overrides below are failing with the following message:
/Users/mark/xcode/X2/Pods/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:542:26: Method does not override any method from its superclass

//////////////////////////
    // MARK: Events
    public override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touching = true
        setNeedsDisplay()
    }
    
    public override func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touching = false
        setNeedsDisplay()
        didTapped()
    }
    
    public override func touchesCancelled(touches: Set<NSObject>!, withEvent event: UIEvent!) {
        self.touching = false
        setNeedsDisplay()
    }

**Comment by yoavlt** [comment]
It is master branch.
Please use `swift-2.0` branch.

**Comment by markgk** [comment]
thanks for the fast response.
I am new to GitHub... so please excuse a novice question.
pod search did show only one branch. what do I put in Podfile to pickup the
swift-2.0 branch?
thank you,
Mark

**Comment by sumitlni** [comment]
@markgk, if it helps, the following worked for me (all in one line):

pod "LiquidFloatingActionButton", :git => 'https://github.com/yoavlt/LiquidFloatingActionButton', :branch => 'swift-2.0'

**Comment by markgk** [comment]
Thanks. works like a charm
