### ISSUE TITLE
Button with Title

### ISSUE THREAD

**Issue by jasvindersingh-evon** [yoavlt/LiquidFloatingActionButton#21]
How to give a left or right side title to the buttons?

**Comment by yoavlt** [comment]
Please see the example project. You can easily add titles.

**Comment by jasvindersingh-evon** [comment]
Thanks for the reply. I checked the example project. I am not familiar with Swift much. And I am not sure what code I must write to display titles to the items. Could you please help me out. I would be very thankful to you.

**Comment by yoavlt** [comment]
OK. 

The following lines define your custom cell with title and layouts.
https://github.com/yoavlt/LiquidFloatingActionButton/blob/swift-2.0/Example/LiquidFloatingActionButton/ViewController.swift#L13-L38

Then, you can create cell as below.
https://github.com/yoavlt/LiquidFloatingActionButton/blob/swift-2.0/Example/LiquidFloatingActionButton/ViewController.swift#L61-L63

**Comment by jasvindersingh-evon** [comment]
Thank you so much. Its my bad, I downloaded the master branch. In Swift 2.0, you have already implemented how to add labels to it. You have designed a great repository.

**Comment by yoavlt** [comment]
You're welcome. I'm sorry for confusing you. :)

**Comment by jasvindersingh-evon** [comment]
Hello,

I somehow managed to give different colors to each individual cell as mentioned below. I added another initializer to give color to each individual cell. But after implementing the below code, the Liquid effect still have the color of the action button. Can you please help me how I can achieve the liquid with the colors given to each cell.

Please check attached video URL
https://www.dropbox.com/s/s0gpjfqosrd4wkx/iTools%20Screen%20Record%202015-11-18%2018.12.56.mov?dl=0

Removed below code 

circleLayer.fillColor = self.color.CGColor 
from 
func draw(path: UIBezierPath) -> CAShapeLayer

so that each individual circle can have a different color.

**Comment by yigitserin** [comment]
Hi there, 

How did you give different colors to each button? Can you share the code ?

**Comment by emouawad** [comment]
Labels are not hit (i.e events), maybe because of the hitTest logic?
