### ISSUE TITLE
How can I use this library with objective-c?

### ISSUE THREAD

**Issue by afiq90** [yoavlt/LiquidFloatingActionButton#22]
How can I use this library with objective-c? thanks.

**Comment by elilien** [comment]
Hi @afiq90 , add `use_frameworks!` this to your Podfile, pod update, then import it! ;-)

**Comment by afiq90** [comment]
I tried but I can't make it work, sorry i'm novice. :)

**Comment by elilien** [comment]
@afiq90 Can you put your error here?

**Comment by deepak-matteroftech** [comment]
How to use this library with Objective-C

**Comment by deepak-matteroftech** [comment]
I've added all swift files manually by using objective c bridging. But now it throwing many types of error (66 errors)

**Comment by yoavlt** [comment]
@deepak-matteroftech Could your describe your environment. If you use Xcode7 or higher, you should use.
