### ISSUE TITLE
Scrolling with the Floating Button

### ISSUE THREAD

**Issue by jefferyleo** [yoavlt/LiquidFloatingActionButton#23]
I just found out that, I've a floating button in a tableView. When I'm trying to scroll the tableView, the floating button doesn't scroll with tableView, it just stick to its position. How do I fix this problem?
![img_0101](https://cloud.githubusercontent.com/assets/6831609/11623886/d9512396-9d0a-11e5-834e-cc553fd512c3.jpg)
![img_0102](https://cloud.githubusercontent.com/assets/6831609/11623887/d99c49de-9d0a-11e5-9d05-6bcb4faf736f.jpg)

**Comment by jasvindersingh-evon** [comment]
Have you added the button on Table View or on a cell?

**Comment by jefferyleo** [comment]
@jasvindersingh-evon I set in the tableView, not in the cell. If it's in the cell, the button will located in the tableView cell, but this is not right?
```
let floatingFrame = CGRect(x: self.view.frame.width - 56 - 16, y: self.view.frame.height - 56 - 80, width: 56, height: 56)
        let bottomRightButton = createFloatButton(floatingFrame, .Up)
        self.view.addSubview(bottomRightButton)
```
This is my code for locating in the tableView. I've added the subView into the tableView. just wondering why it's not stick to the position, it will moves when I'm scrolling.

**Comment by yoavlt** [comment]
@jefferyleo If you want to stick to the position, you should use UIWindow or other.

**Comment by jefferyleo** [comment]
@yoavlt Any example of UIWindows to make this button stick at the fixed position?

**Comment by yoavlt** [comment]
@jefferyleo Otherwise, you can also do hierarchy views as follows.
UIView
  -- LiquidFloatingActionButton
  -- UITableView

**Comment by jefferyleo** [comment]
@yoavlt I'm sorry for telling you that I'm still a beginner in iOS programming, could you give me some clue regarding the similar code to me?

**Comment by yoavlt** [comment]
@jefferyleo OK. This is example!!
https://gist.github.com/yoavlt/393a0bce0536e926b01d

**Comment by jefferyleo** [comment]
@yoavlt Thanks dude, I'm appreciate, I will try to do it now see whether I got it or not :+1: will support your project always!

**Comment by jefferyleo** [comment]
@yoavlt May I know what this line of code means?
```
tableView.snp_makeConstraints { make in
            make.width.height.top.left.equalTo(self.view)
        }
```
As I know, tableView don't have a function called snp_makeConstraints

**Comment by yoavlt** [comment]
@jefferyleo It's [SnapKit](https://github.com/SnapKit) extension. You can also use AutoLayout.

**Comment by jefferyleo** [comment]
Opps, I knew that, it's SnapKit extension hahaha I just found out that. Thank you

**Comment by jefferyleo** [comment]
@yoavlt I failed to do it.
```
make.width.height.top.left.equalTo(self.view)
```
There's an error on this line.
> fatal error: unexpectedly found nil while unwrapping an Optional value
I've no idea why there's an optional value at this line, that's quite weird.

**Comment by yoavlt** [comment]
@jefferyleo It's totally odd. :sob:

**Comment by jefferyleo** [comment]
@yoavlt I got a clue from this Question.
http://stackoverflow.com/questions/13663230/ios-add-subview-with-a-fix-position-on-screen
We can try to do it by this way. Let's try.

**Comment by jefferyleo** [comment]
@yoavlt Are you manage to do it with the scrollViewDidScroll method?

**Comment by yoavlt** [comment]
@jefferyleo No, I didn't. It works for my environment.

**Comment by jasvindersingh-evon** [comment]
@jefferyleo: self.view is your tableview I guess, And adding it on self.view means you are adding it on tableview. So whenever the UITableView will scroll, the button will scroll with it. If you want to add it. Add it on self.view considering self.view should not be a TableView. Please attach the XIB/storyboard screenshot with outline hierarchy displayed.

**Comment by jefferyleo** [comment]
@jasvindersingh-evon then do you know how do I stick to the scrollView, since the scrollView has also a delegate from the tableViewController.

**Comment by yoavlt** [comment]
@jefferyleo I know. You should use UIViewController instead of UITableViewController.

**Comment by jefferyleo** [comment]
@yoavlt But..I want to list all the news in a tableView instead of ViewController, that's why I have to use UITableViewController in necessary. :(

**Comment by jasvindersingh-evon** [comment]
Understood. Do one thing. Delete the UITableViewController and take a new UIViewController. In that View controller add a UITableView. Then add the button on that view controller. Set Delegate and data source of UITableView to File's Owner. And everything will work. Let me know if this doesn't works for you.

**Comment by yoavlt** [comment]
@jefferyleo I agree with @jasvindersingh-evon's solution.

**Comment by jefferyleo** [comment]
@jasvindersingh-evon Okay, I'll try that later, will get back to you soon, I fixing another problem first. :(

**Comment by jefferyleo** [comment]
@yoavlt @jasvindersingh-evon Okay, good news here! I did it hahaha Thanks a lot dude, appreciated. :+1:

**Comment by yoavlt** [comment]
@jefferyleo Congrats! :+1:

**Comment by harry-77** [comment]
@jefferyleo  Is your problem solved ?

**Comment by harry-77** [comment]
@jefferyleo  How you reorder these cell ?

**Comment by harry-77** [comment]
//below implementation is for adding floating button while subclassing UITableViewController 

var addMoreImageBtn : UIButton?

 override func viewDidLoad() {
        super.viewDidLoad()

        addMoreImageBtn = UIButton(type: .Custom)
        addMoreImageBtn?.setImage(UIImage(named: "Add.png"), forState: .Normal)
        addMoreImageBtn?.frame = CGRectMake(0, self.view.bounds.size.height - 100, 55, 55)
        
        addMoreImageBtn?.center = CGPointMake(self.view.bounds.width - 100 , self.view.bounds.size.height - 100)

        addMoreImageBtn?.addTarget(self, action: "addButtonPressed:", forControlEvents: .TouchUpInside)

        self.view.addSubview(addMoreImageBtn!)
    }

 override func scrollViewDidScroll(scrollView: UIScrollView) {        
        addMoreImageBtn?.frame.origin.y = self.view.bounds.size.height - 100 + scrollView.contentOffset.y
        
        self.view.addSubview(addMoreImageBtn!)
        self.view.bringSubviewToFront(addMoreImageBtn!)
               
    }
