### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by artiy** [yoavlt/LiquidFloatingActionButton#24]
After pod installation of LiquidFloatingButtonAction, I am getting  "Method does not override any method from its superclass" error in my project multiple times. Can you please whats wrong with my project?

**Comment by diogo10** [comment]
The same here..

**Comment by amukbils** [comment]
same here

**Comment by RTimal** [comment]
It has to do with the new version of Swift, the method signatures are different.

**Comment by Jackson0111** [comment]
solution in #20
