### ISSUE TITLE
Is there a way to change the speed when button is tapped?

### ISSUE THREAD

**Issue by Jackson0111** [yoavlt/LiquidFloatingActionButton#28]
I wanna say thank you! This is great, I'm loving it and I appreciate your work. I was just looking through the code but couldn't find a way to change the speed when button is tapped, is there a way to do that?

**Comment by mrfeiii** [comment]
chang the openDuration and closeDuration below to customize the speed.

class CircleLiquidBaseView : ActionBarBaseView {
    let openDuration: CGFloat  = 0.4
    let closeDuration: CGFloat = 0.2
    let viscosity: CGFloat     = 0.65
    var animateStyle: LiquidFloatingActionButtonAnimateStyle = .Up
    var color: UIColor = UIColor(red: 82 / 255.0, green: 112 / 255.0, blue: 235 / 255.0, alpha: 1.0) {
        didSet {
            engine?.color = color
            bigEngine?.color = color
        }
    }
