### ISSUE TITLE
Error Found

### ISSUE THREAD

**Issue by Sadmansamee** [yoavlt/LiquidFloatingActionButton#31]
For these functions I'm getting error and error message is "LiquidFloatingActionButton.swift:201:26: Method does not override any method from its superclass"

    // MARK: Events
    public override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touching = true
        setNeedsDisplay()
    }
    
    public override func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touching = false
        setNeedsDisplay()
        didTapped()
    }
    
    public override func touchesCancelled(touches: Set<NSObject>!, withEvent event: UIEvent!) {
        self.touching = false
        setNeedsDisplay()
    }

**Comment by mrfeiii** [comment]
solution in https://github.com/yoavlt/LiquidFloatingActionButton/issues/20
