### ISSUE TITLE
Pretty laggy 

### ISSUE THREAD

**Issue by yuwang17** [yoavlt/LiquidFloatingActionButton#32]
Really nice animation but I am wondering why is pretty laggy now, same problem for Demo? I'm using swift 2 in iOS 9.

**Comment by mrfeiii** [comment]
Yes,when you run in simulator it's laggy, but no, when you run in real device

**Comment by yuwang17** [comment]
Yeah, that's true. Thanks! REALLY NICE EFFECT!
