### ISSUE TITLE
Enhancement : Add information text to LiquidFloatingCell 

### ISSUE THREAD

**Issue by deathslocus** [yoavlt/LiquidFloatingActionButton#36]
Just thought it would be nice to be able to have a small line of text telling users what the button does inline with the LiquidFloatingCell.

I am going to have a go at implementing it but thought I'd put it here in case anyone else has something for it.

**Comment by yoavlt** [comment]
OK. Have you tried to customize cell like this?
https://github.com/yoavlt/LiquidFloatingActionButton/blob/swift-2.0/Example/LiquidFloatingActionButton/ViewController.swift#L61-L63

**Comment by deathslocus** [comment]
Sweet exactly what I wanted, silly me I didn't check the examples.
