### ISSUE TITLE
Carthage - Build Failed

### ISSUE THREAD

**Issue by krazie99** [yoavlt/LiquidFloatingActionButton#45]
If I use Carthage to install LiquidFloatingActionButton.
There are some errors when build it.

```
LiquidFloatingActionButton.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:196:26: error: method does not override any method from its superclass
```

Please, check this and fix please.
Thank you.

**Comment by awesomeswift** [comment]
the same, please fix

**Comment by awesomeswift** [comment]
@krazie99 ,
you should edit the Cartfile,
try this : github "yoavlt/LiquidFloatingActionButton" "swift-2.0"

Regards,

**Comment by yoavlt** [comment]
Thanks @awesomeswift !!

**Comment by krazie99** [comment]
@awesomeswift Thanks !
