### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by AZmake** [yoavlt/LiquidFloatingActionButton#49]
public override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touching = true
        setNeedsDisplay()
    }
swift:196:26: Method does not override any method from its superclass

Is there something has changed in swift? My Xcode Version 7.2.1 (7C1002).

**Comment by yoavlt** [comment]
Please use `swift-2.0` branch.

**Comment by AZmake** [comment]
thanks!
