### ISSUE TITLE
Carthage build issue (Xcode 7.3)

### ISSUE THREAD

**Issue by karuna2302** [yoavlt/LiquidFloatingActionButton#54]
The following build commands failed:
	CompileSwift normal arm64 XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:196:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:201:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:207:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:527:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:535:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:542:26: error: method does not override any method from its superclass
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:77:15: error: a non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:176:13: warning: variable 'paths' was never mutated; consider changing to 'let' constant
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:251:16: warning: value 'source' was defined but never used; consider replacing with boolean test
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:326:61: warning: use '#selector' instead of explicitly constructing a 'Selector'
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:325:13: warning: initialization of immutable value 'distance' was never used; consider replacing with assignment to '_' or removing it
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:340:61: warning: use '#selector' instead of explicitly constructing a 'Selector'
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:338:13: warning: initialization of immutable value 'distance' was never used; consider replacing with assignment to '_' or removing it
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:446:13: warning: initialization of variable 't2' was never used; consider replacing with assignment to '_' or removing it
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift:520:35: warning: conditional cast from 'UIView' to 'UIView' always succeeds
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/SimpleCircleLiquidEngine.swift:121:22: warning: immutable value '_d1' was never used; consider replacing with '_' or removing it
XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/SimpleCircleLiquidEngine.swift:122:22: warning: immutable value '_d2' was never used; consider replacing with '_' or removing it
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 XX/Carthage/Checkouts/LiquidFloatingActionButton/Pod/Classes/LiquidFloatingActionButton.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by yoavlt** [comment]
Could you try `carthage update --platform iOS --no-use-binaries` ?

**Comment by cklab** [comment]
@karuna2302 Looks like you're using swift 2.0, remember to use the swift-2.0 branch

**Comment by hexfa** [comment]
you should edit the Cartfile,
add this : github "yoavlt/LiquidFloatingActionButton" "swift-2.0"
check this link: https://github.com/yoavlt/LiquidFloatingActionButton/issues/45

regards,

**Comment by SamiraElhami** [comment]
you should edit the Cartfile,
add this : github "yoavlt/LiquidFloatingActionButton" "swift-2.0"
check this link: #45

regards,
