### ISSUE TITLE
Showing one extra circles while using in storyboard

### ISSUE THREAD

**Issue by vijaysanghavi** [yoavlt/LiquidFloatingActionButton#55]
Please see the image for bug,

![screen shot 2016-04-01 at 12 30 00 pm](https://cloud.githubusercontent.com/assets/7793810/14200312/9aff3f62-f807-11e5-9536-80c86ce96d9c.png)

I added a `UIView` in storyboard and set its class to `LiquidFloatingActionButton`. It is showing floating button but with an extra large circle besides it.

**Comment by OxyFlax** [comment]
Hello, 
I think you added this second button in your code. 
You should drag your item in your code and then use this name instead of an other you created in your code.

**Comment by vijaysanghavi** [comment]
@OxyFlax I have clearly mentioned that I added a `UIView` in storyboard and set its class to `LiquidFloatingActionButton`. I have not written a single line of code yet to perform any actions it's just the snapshot of newly created project.

**Comment by OxyFlax** [comment]
You could have look at the example code and added a UIView in the storyboard. Sorry but your description was not clear.
You should try with the provided example.

**Comment by vijaysanghavi** [comment]
Well I followed the example and found all same but the constraints, the problem was with the constraints in landscape and portrait mode. Thanks by the way.
