### ISSUE TITLE
no such module LiquidFloatingActionButton

### ISSUE THREAD

**Issue by sphairo** [yoavlt/LiquidFloatingActionButton#58]
I am using objc and my podfile has :

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Test' do
   pod 'LiquidFloatingActionButton'
end

target 'TestTests' do

end

target 'TestUITests' do

end

But not working :(

**Comment by econ5000** [comment]
I'm seeing the same issue, my Podfile lookst like the below (I am using swift)

platform :ios, '9.0'
use_frameworks!

target 'PhotoSwipe Lock!' do
   pod "LiquidFloatingActionButton"
end

**Comment by econ5000** [comment]
I'm seeing the same issue, my podfile looks like this

platform :ios, '9.0'
use_frameworks!

target 'Test' do
   pod "LiquidFloatingActionButton"
end

**Comment by econ5000** [comment]
OK, looks like my issue was due to cocoapods installing the incorrect version I needed (I think it installed the master version, and I needed swift-2.0

**Comment by yoavlt** [comment]
I updated cocoapod !! 👍
