### ISSUE TITLE
Minimum deployment target 8.3?

### ISSUE THREAD

**Issue by waniwang** [yoavlt/LiquidFloatingActionButton#6]
The minimum deploy target is 8.3?
Is downward compatibility to iOS 7.0 feasible?

<img width="1107" alt="2015-09-08 9 38 24" src="https://cloud.githubusercontent.com/assets/2967208/9724558/ca5a1c66-560c-11e5-9e10-085cb6ec8074.png">

**Comment by yoavlt** [comment]
Thank you for your issue! Dynamic framework is not supported for iOS 7.0.
But I supported iOS8.0+ for minimum deployment target. Please update my library.
