### ISSUE TITLE
Cathage update fails! 

### ISSUE THREAD

**Issue by Dershowitz011** [yoavlt/LiquidFloatingActionButton#61]
Carthage update fails with 2 commands. There is something really wrong with the `LiquidFloatingButton` class. Please fix it.

**Comment by canatac** [comment]
Same for me : need minor fixes in LiquidFloatingActionButton.swift file.
After correcting locally, it compiles fine with 

`carthage build` command

1. Need a '?' in required init method
`required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }` 

2. In LiquidFloatingActionButton and LiquidFloatingCell classes : 
Touches override functions need an update : 

`public override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent)`   must change into 
`public override func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {` 

Same for `touchesEnded` and `touchesCancelled` methods.

**Comment by canatac** [comment]
Ok, I was pulling the master branch.
Need to update `Cartfile` by specifying swift-2.0 branch : 
`github "yoavlt/LiquidFloatingActionButton" "swift-2.0"`

**Comment by yoavlt** [comment]
Updated `master` branch 👌
