### ISSUE TITLE
This lib only works with Cocoapods?

### ISSUE THREAD

**Issue by helenamcfreire** [yoavlt/LiquidFloatingActionButton#62]
Hello guys,

Im trying to use this lib in my swift project, but ONLY at device (iphone 5) it is crashing. At simulator is working fine. I dont use Cocoapods in my project, can be it ? Is there something Im doing wrong?

Swift 2.2
Xcode 7.3
Tested on iPhone 5 (iOS 9.3.1)

**Comment by yoavlt** [comment]
It is odd behavior.
Could you tell me crash message?

**Comment by helenamcfreire** [comment]
Im sorry Takuma, I was doing shit. :(

Thanks for the reply!

Kisses

**Comment by yoavlt** [comment]
Thanks :D
