### ISSUE TITLE
Can not run because library not loaded.

### ISSUE THREAD

**Issue by lynnx4869** [yoavlt/LiquidFloatingActionButton#68]
I installed it by CocoaPods. I added the following line to your Podfile:
`pod 'LiquidFloatingActionButton', :git => 'https://github.com/yoavlt/LiquidFloatingActionButton.git', :branch => 'swift-2.0'`
And installed it.
But run it, it must crash.
This is a error:
![](https://lh4.googleusercontent.com/-ZqGlFuRLLMM/V1feK2QlOgI/AAAAAAAAADQ/nhuZEJiiSsgn4KnK985E_60Q7SGCZydEQCL0B/w1020-h586-no/QQ20160608-0.png)
I want to help!!

**Comment by yoavlt** [comment]
Please ensure to use `*.xcworkspace` for project file and target schema correctly.

**Comment by lynnx4869** [comment]
@yoavlt I sure to use `*.xcworkspace`. I can use other librarys like Alamofire. But i can't use it.

**Comment by yoavlt** [comment]
Thank you for your reply!
Did you run `pod install` ?

**Comment by lynnx4869** [comment]
@yoavlt Yeah, I use it. It had been installed.

**Comment by yoavlt** [comment]
I can't figure out why it is happening... Did it occur both in device and simulator?

**Comment by lynnx4869** [comment]
@yoavlt Well, I only tried it in simulator and will try it in device. I should tell you result after done it.

**Comment by lynnx4869** [comment]
@yoavlt Well, I change a Mac and can use it...

**Comment by yoavlt** [comment]
@lynnx4869 I see. Thanks for reporting. :D
