### ISSUE TITLE
Can Objective-C invoke this component?

### ISSUE THREAD

**Issue by nickevin** [yoavlt/LiquidFloatingActionButton#7]

**Comment by vikdenic** [comment]
How can this Cocoapod be used in an Objective-C project?

**Comment by mofodox** [comment]
@vikdenic Hey, maybe you should check this out [thread from stackoverflow](http://stackoverflow.com/a/26873548) if you want to integrate Swift code in Objective-C :smile:

I hope it helps :v:

**Comment by tsambora** [comment]
Kinda hoping for it to be written in Obj-C.

**Comment by mofodox** [comment]
Hey @tsambora, it's easy for you to get it up and running in Objective-C project.

**Comment by Big-al** [comment]
Hey!
Im trying to implement it in my objective C project - but it naturally won't work with:
let floatingActionButton = LiquidFloatingActionButton(frame: floatingFrame)
floatingActionButton.dataSource = self
floatingActionButton.delegate = self

Any thoughts of what else i could use? Im brand new to iOS programming (but i love learning), so bear with me.

**Comment by yoavlt** [comment]
@Big-al You need to implement with Objective-C.

**Comment by Big-al** [comment]
I use #import "LiquidFloatingActionButton-Swift.h" in my view controller but i get an "undeclared type" for the let

**Comment by yoavlt** [comment]
@Big-al I think that you should use "YourProjectName-Swift.h".

**Comment by Big-al** [comment]
well this is to import the liquidfloatingactionbutton into my own project - wouldn't i then import LiquidFloatingActionButton-Swift.h into my viewcontroller of my original project? Or am i completely wrong on the syntax?

**Comment by yoavlt** [comment]
@Big-al Do you use in Objective-C file (*.m) ? And if so, you should use Objective-C syntax.

**Comment by Big-al** [comment]
Im trying that now with LiquidFloatingActionButton *floatingActionButton = [[LiquidFloatingActionButton alloc] initWithFrame: floatingFrame];
    floatingActionButton.dataSource = self;
    floatingActionButton.delegate = self;

**Comment by yoavlt** [comment]
@Big-al Did you declare a `floatingFrame` variable?

**Comment by Big-al** [comment]
By using the "@interface floatingFrame" right?

**Comment by yoavlt** [comment]
@Big-al 
Example is the following.
```Objective-C
CGRect* floatingFrame = CGRectMake(0, 0, 50, 50);
```

**Comment by SSA111** [comment]
CGRect floatingFrame = CGRectMake(0,0,100,100); 
LiquidFloatingActionButton *floatingActionButton = [[LiquidFloatingActionButton alloc] initWithFrame: floatingFrame];
floatingActionButton.dataSource = self;
floatingActionButton.delegate = self;

**Comment by Big-al** [comment]
Ah okay! and that tells Xcode where to place the button? 

Sorry for the questions again. I run a startup, and up until now I've been a web developer and graphic designer, as well as the CEO of the company. We are building an app, what it does is not really important, but we had it all developed by 3-4 different companies that fooled us into thinking they were able to make it happen. none of them could and it ended up costing me all my savings. So here i am trying to learn how to do it myself - you gotta start somewhere! So i appreciate you all helping me out, even though it might be some noob questions :+1:

**Comment by yoavlt** [comment]
@Big-al It's right! I also run a startup. I appreciate you use my library! :+1:

**Comment by Big-al** [comment]
Awesome! I appreciate you sharing it!

**Comment by Big-al** [comment]
Now im getting this: 
![skaermbillede 2015-10-16 kl 17 06 38](https://cloud.githubusercontent.com/assets/7080878/10545312/5cb36ade-7428-11e5-9231-bb5d096f0839.png)

And the Button is not displayed in my app for some reason!

**Comment by yoavlt** [comment]
@Big-al You need to add `addSubview` to displaying view, and implement `LiquidFloatingActionButtonDataSource` and `LiquidFloatingActionButtonDelegate` protocols.

**Comment by Big-al** [comment]
Hey! Thats a Swift only function tho isn't it?

**Comment by Big-al** [comment]
So, i added the following to my viewControllers.m file:
#import "LiquidFloatingActionButton-Swift.h"

@synthesize LiquidFloatingActionButtonDelegate;
@synthesize LiquidFloatingActionButtonDataSource;

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self.view addSubview:LiquidFloatingActionButtonDataSource];
    [self.view addSubview:LiquidFloatingActionButtonDelegate];

--and the following to my viewControllers.h file:

#import "LiquidFloatingActionButton-Swift.h"

@property (nonatomic, strong)UIView *LiquidFloatingActionButtonDataSource;
@property (nonatomic, strong)UIView *LiquidFloatingActionButtonDelegate;

I GET NO ERRORS! YAY
However nothing appears still - am i missing something?

**Comment by yoavlt** [comment]
@Big-al 
Reference:
https://github.com/yoavlt/LiquidFloatingActionButton/blob/master/Example/LiquidFloatingActionButton/ViewController.swift#L42

**Comment by Big-al** [comment]
That is swift though? i can't implement it directly can i?

**Comment by yoavlt** [comment]
@Big-al Let's learn `protocol` and `UIKit` basics. UITableView tutorial including `UITableViewDelegate` and `UITableViewDataSource` should help you.

**Comment by Big-al** [comment]
thx, will try!

**Comment by GutteApps** [comment]
@yoavlt I've implemented your library in objective-c and was able to display the floating button and  customise a few cells. The LiquidFloatingActionButtonDataSource methods are called. However, the LiquidFloatingActionButtonDelegate method: -(void)liquidFloatingActionButton:(LiquidFloatingActionButton *)liquidFloatingActionButton didSelectItemAtIndex:(NSInteger)index;
is never called. (I've set my controller to be the floating button delegate) Any ideas why?

-(void)setFloatingButton{
    LiquidFloatingActionButton *floatingActionButton = [[LiquidFloatingActionButton alloc] initWithFrame:CGRectMake(kScreenWidth-70, kScreenHeight-70, 50, 50)];
    floatingActionButton.dataSource = self;
    floatingActionButton.delegate = self;
    [self.view addSubview:floatingActionButton];   
}

#pragma mark - LiquidFloatingActionButtonDataSource
-(NSInteger)numberOfCells:(LiquidFloatingActionButton *)liquidFloatingActionButton{
    return 2;
}

-(LiquidFloatingCell *)cellForIndex:(NSInteger)index{
  
    LiquidFloatingCell *cell;
    
    switch (index) {
        case 0:
            
            cell = [[LiquidFloatingCell alloc]initWithIcon:[UIImage imageNamed:@"foot_delete_icon"]];
            
            break;
        case 1:
            
            cell = [[LiquidFloatingCell alloc]initWithIcon:[UIImage imageNamed:@"ic_mark_read"]];
            
            break;
            
        default:
            break;
    }
    
    return cell;
}

#pragma mark - LiquidFloatingActionButtonDelegate
-(void)liquidFloatingActionButton:(LiquidFloatingActionButton *)liquidFloatingActionButton didSelectItemAtIndex:(NSInteger)index{
    
    [liquidFloatingActionButton close];
}

**Comment by yoavlt** [comment]
@GutteApps Sorry, I can't reproduce it. I can't understand its bugs.

**Comment by McExco** [comment]
@GutteApps May be it's a little to late. I had the same problem as you. And I figured out what caused the problem: you need to store cell object in array, so it can be referenced back.

```
- (void)addLiquidButton{
liquidCells = [[NSMutableArray alloc] init];
[liquidCells addObject:[[LiquidFloatingCell alloc]initWithIcon:[UIImage imageNamed:@"foot_delete_icon"]]];
    
floatingActionButton = [[LiquidFloatingActionButton alloc] initWithFrame:CGRectMake(100, 300, 50, 50)];
floatingActionButton.dataSource = self;
floatingActionButton.delegate = self;
floatingActionButton.userInteractionEnabled = YES;
[self.view addSubview:floatingActionButton];
}

-(NSInteger)numberOfCells:(LiquidFloatingActionButton *)liquidFloatingActionButton{
    return liquidCells.count;
}

-(LiquidFloatingCell *)cellForIndex:(NSInteger)index{
    return [liquidCells objectAtIndex:index];
}
```

This way 'liquidFloatingActionButton' delegate will be called.
