### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by XinwenCheng** [yoavlt/LiquidFloatingActionButton#71]
Hi guys,

I met 7 errors when I just build project with LiquidFloatingActionButton, and I checked, this class inherits from UIView, but there's no **touchesBegan, touchesEnded, touchesCancelled** methods in it, and another error says **a non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'**.

Maybe this relates to Swift's version, my XCode is V7.3.1 (7D1014) and Swift should be V2.2. I like your component, would you please help to check this? Thanks very much!

**Comment by yoavlt** [comment]
Please specify `swift-2.0` branch for installation of this module.

**Comment by XinwenCheng** [comment]
Thanks @yoavlt ! Sorry I didn't notice that sentence in document.
