### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by XinwenCheng** [yoavlt/LiquidFloatingActionButton#73]
How could I change the background color of floating action button?

**Comment by savionsample** [comment]
Go to LiquidFloatingActionButton.swift and look at:

`@IBInspectable public var color: UIColor = UIColor(red: 36 / 255.0, green: 42 / 255.0, blue: 70 / 255.0, alpha: 1.0) {
        didSet {
            baseView.color = color
        }
    }`

There you can change the rgb color value and whatnot to your liking.

**Comment by japhethkosgei** [comment]
In case anyone still needs to do this... 
You can also set the color value on your instance of floating action button like this:

`myFloatingActionButton.color = UIColor.green`

Of course use your choice of color.

**Comment by NikhilGangurde** [comment]
In my case, I have to give custom color so I used to like this using @japhethkosgei  answer

`floatingActionButton.color = UIColor(red:250.0/255.0, green:75.0/255.0, blue:150.0/255.0, alpha:1.0)`

**Comment by XinwenCheng** [comment]
Thanks both @japhethkosgei and @NikhilGangurde very much!

**Comment by NikhilGangurde** [comment]
> Thanks both @japhethkosgei and @NikhilGangurde very much!

you're welcome!!
