### ISSUE TITLE
A couple of warnings in Xcode for Swift 2.0 branch

### ISSUE THREAD

**Issue by mofodox** [yoavlt/LiquidFloatingActionButton#8]
Hello,

I used the Swift 2.0 branch to check out this awesome library. I received warnings about some variables are not used. Is it possible if I can do some changes to the code and send it as a pull request?

Thank you! :smile:

**Comment by yoavlt** [comment]
Awesome! Thanks!

**Comment by adrianchifor** [comment]
I'm not just getting warnings, I'm also getting a few issues and it fails to build (a few 'Method does not override method from its superclass' and 'A non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'').

**Comment by yoavlt** [comment]
I removed warnings.
