### ISSUE TITLE
Error in swift 3.0

### ISSUE THREAD

**Issue by AlbertoMrFz** [yoavlt/LiquidFloatingActionButton#84]
I have this problem with swift 3 and xcode 8

![error liquid floating](https://cloud.githubusercontent.com/assets/9303324/18662904/8ccf6cc2-7f1c-11e6-9ca9-df3cbcdcbf14.PNG)

**Comment by AlbertoMrFz** [comment]
I need help for this error

**Comment by kevinlu1211** [comment]
I think you just need to change the variable name in the UIColorEx file since Apple changed UIcolor.redColor() to just UIColor.red
