### ISSUE TITLE
Swift 3+ support

### ISSUE THREAD

**Issue by despie** [yoavlt/LiquidFloatingActionButton#91]
The project uses SnapKit pod library which doesn't support swift 3. Podfile has to be updated to something like:

> pod ‘SnapKit’, ‘>= 3.0.0’

Currently SnapKit library used in this project supports only Swift 2.3.

**Comment by lazar108** [comment]
do you mind looking at my issue here:

http://stackoverflow.com/questions/39947980/cant-configure-datasource-and-delegate

I feel like I'm the only one with this problem but it seems like other people are having issues too
